name: chat_new
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.1.0
  firebase_core: ^1.22.0
  firebase_auth: ^3.4.2
  lottie: ^1.3.0
  flutter_screenutil: ^5.5.3+2
  carousel_slider: ^4.1.1
  cool_alert: ^1.1.0
  flutter_riverpod: ^2.0.0-dev.9
  percent_indicator: ^4.2.2
  intro_slider: ^3.0.9
  grouped_list: ^4.2.0
  intl: ^0.17.0
  bubble: ^1.2.1
  cloud_firestore: ^3.4.8
 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Calisto
      fonts:
        - asset: fonts/calistomt.ttf
 