///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UsersModelKisiler {
  int? id;
  String? name;
  String? surname;
  String? imagePath;
  String? gender;
  bool? online;
  String? location;

  UsersModelKisiler({
    this.id,
    this.name,
    this.surname,
    this.imagePath,
    this.gender,
    this.online,
    this.location,
  });
  UsersModelKisiler.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    surname = json['surname']?.toString();
    imagePath = json['imagePath']?.toString();
    gender = json['gender']?.toString();
    online = json['online'];
    location = json['location']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['surname'] = surname;
    data['imagePath'] = imagePath;
    data['gender'] = gender;
    data['online'] = online;
    data['location'] = location;
    return data;
  }
}

class UsersModel {
  List<UsersModelKisiler?>? kisiler;

  UsersModel({
    this.kisiler,
  });
  UsersModel.fromJson(Map<String, dynamic> json) {
    if (json['kisiler'] != null) {
      final v = json['kisiler'];
      final arr0 = <UsersModelKisiler>[];
      v.forEach((v) {
        arr0.add(UsersModelKisiler.fromJson(v));
      });
      kisiler = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (kisiler != null) {
      final v = kisiler;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['kisiler'] = arr0;
    }
    return data;
  }
}
